[package]
name = "modcraft_lib"
version = "0.1.0"
authors = ["Josh Bedwell <rcxwhiz@gmail.com>"]
edition = "2021"
rust-version = "1.73"
description = "A library that the game ModCraft and its mods depend on."

[dependencies]
